#!/bin/bash -e

if [ "X$1" == "Xfullconf" ];then
	pushd ../CursesToolKit
	./autogen.sh
	sudo make distclean
	CFLAGS="-g -O0" CXXFLAGS="-g -O0" ./configure --prefix=/usr --enable-debug
	make -j4
	exit 0
fi

if [ "X$1" == "Xconf" ];then
	make distclean || true
	rm -rf FBMediaPlayer/src/.deps
	CURSESTOOLKIT_CFLAGS="-I../../../CursesToolKit/CursesToolKit/src" LDFLAGS="-L../../../CursesToolKit/CursesToolKit/lib/.libs" CFLAGS="$CURSESTOOLKIT_CFLAGS -g -O0" CXXFLAGS="$CURSESTOOLKIT_CFLAGS -g -O0 -Wunused-variable" ./autogen.sh --prefix=/usr --datadir=/media/LinuxData/Development64/Projects/FBMediaPlayer/FBMediaPlayer/resources
else
	if [ "X$1" = "Xmake" ];then
		(cd ../CursesToolKit/;make -j4)
			(
				cd FBMediaPlayer/app
				make -j1 || exit 100
			)
		exit 0
	fi

	if [ "${USEVAL:-0}" -eq 1 ];then
		USEVALGRIND="valgrind --leak-check=full --suppressions=./ignorelibleaks -s"
	fi
 #--undef-value-errors=no
	(cd ../CursesToolKit/;make -j4)
	(
		cd FBMediaPlayer/app
		make -j1
	)
	eval LD_LIBRARY_PATH=../CursesToolKit/CursesToolKit/lib/.libs ${USEVALGRIND} FBMediaPlayer/app/fbmediaplayer $@
fi

exit 0
